using MapleStory.NET.Objects.CharacterModels.Character;
using MapleStory.NET.Objects.CharacterModels.CharacterBasic;
using MapleStory.NET.Objects.CharacterModels.CharacterHyperStat;
using MapleStory.NET.Objects.CharacterModels.CharacterPopularity;
using MapleStory.NET.Objects.CharacterModels.CharacterStat;
using MapleStory.NET.Objects.CharacterModels.CharacterPropensity;
using MapleStory.NET.Objects.CharacterModels.CharacterAbility;
using MapleStory.NET.Objects.CharacterModels.CharacterItemEquipment;
using MapleStory.NET.Objects.CharacterModels.CharacterCashItemEquipment;
using MapleStory.NET.Objects.CharacterModels.CharacterSymbolEquipment;
using MapleStory.NET.Objects.CharacterModels.CharacterSetEffect;
using MapleStory.NET.Objects.CharacterModels.CharacterBeautyEquipment;
using MapleStory.NET.Objects.CharacterModels.CharacterAndroidEquipment;
using MapleStory.NET.Objects.CharacterModels.CharacterPetEquipment;
using MapleStory.NET.Objects.CharacterModels.CharacterSkill;
using MapleStory.NET.Objects.CharacterModels.CharacterLinkSkill;
using MapleStory.NET.Objects.CharacterModels.CharacterVMatrix;
using MapleStory.NET.Objects.CharacterModels.CharacterHexaMatrix;
using MapleStory.NET.Objects.CharacterModels.CharacterHexaMatrixStat;
using MapleStory.NET.Objects.CharacterModels.CharacterDojang;
using MapleStory.NET.Objects;

namespace MapleStory.NET.Interfaces.Api;
public interface ICharacterApi
{
    Task<CallResult<Character>> GetAsync(string characterName, CancellationToken ct = default);
    Task<CallResult<CharacterBasic>> GetBasicAsync(string ocid, CancellationToken ct = default);
    Task<CallResult<CharacterBasic>> GetBasicAsync(string ocid, DateOnly date, CancellationToken ct = default);
    Task<CallResult<CharacterPopularity>> GetPopularityAsync(string ocid, CancellationToken ct = default);
    Task<CallResult<CharacterPopularity>> GetPopularityAsync(string ocid, DateOnly date, CancellationToken ct = default);
    Task<CallResult<CharacterStat>> GetStatAsync(string ocid, CancellationToken ct = default);
    Task<CallResult<CharacterStat>> GetStatAsync(string ocid, DateOnly date, CancellationToken ct = default);
    Task<CallResult<CharacterHyperStat>> GetHyperStatAsync(string ocid, CancellationToken ct = default);
    Task<CallResult<CharacterHyperStat>> GetHyperStatAsync(string ocid, DateOnly date, CancellationToken ct = default);
    Task<CallResult<CharacterPropesity>> GetPropensityAsync(string ocid, CancellationToken ct = default);
    Task<CallResult<CharacterPropesity>> GetPropensityAsync(string ocid, DateOnly date, CancellationToken ct = default);
    Task<CallResult<CharacterAbility>> GetAbilityAsync(string ocid, CancellationToken ct = default);
    Task<CallResult<CharacterAbility>> GetAbilityAsync(string ocid, DateOnly date, CancellationToken ct = default);
    Task<CallResult<CharacterItemEquipment>> GetItemEquipmentAsync(string ocid, CancellationToken ct = default);
    Task<CallResult<CharacterItemEquipment>> GetItemEquipmentAsync(string ocid, DateOnly date, CancellationToken ct = default);
    Task<CallResult<CharacterCashItemEquipment>> GetCashItemEquipmentAsync(string ocid, CancellationToken ct = default);
    Task<CallResult<CharacterCashItemEquipment>> GetCashItemEquipmentAsync(string ocid, DateOnly date, CancellationToken ct = default);
    Task<CallResult<CharacterSymbolEquipment>> GetSymbolEquipmentAsync(string ocid, CancellationToken ct = default);
    Task<CallResult<CharacterSymbolEquipment>> GetSymbolEquipmentAsync(string ocid, DateOnly date, CancellationToken ct = default);
    Task<CallResult<CharacterSetEffect>> GetSetEffectAsync(string ocid, CancellationToken ct = default);
    Task<CallResult<CharacterSetEffect>> GetSetEffectAsync(string ocid, DateOnly date, CancellationToken ct = default);
    Task<CallResult<CharacterBeautyEquipment>> GetBeautyEquipmentAsync(string ocid, CancellationToken ct = default);
    Task<CallResult<CharacterBeautyEquipment>> GetBeautyEquipmentAsync(string ocid, DateOnly date, CancellationToken ct = default);
    Task<CallResult<CharacterAndroidEquipment>> GetAndroidEquipmentAsync(string ocid, CancellationToken ct = default);
    Task<CallResult<CharacterAndroidEquipment>> GetAndroidEquipmentAsync(string ocid, DateOnly date, CancellationToken ct = default);
    Task<CallResult<CharacterPetEquipment>> GetPetEquipmentAsync(string ocid, CancellationToken ct = default);
    Task<CallResult<CharacterPetEquipment>> GetPetEquipmentAsync(string ocid, DateOnly date, CancellationToken ct = default);
    Task<CallResult<CharacterSkill>> GetSkillAsync(string ocid, string characterSkillGrade, CancellationToken ct = default);
    Task<CallResult<CharacterSkill>> GetSkillAsync(string ocid, DateOnly date, string characterSkillGrade, CancellationToken ct = default);
    Task<CallResult<CharacterLinkSkill>> GetLinkSkillAsync(string ocid, CancellationToken ct = default);
    Task<CallResult<CharacterLinkSkill>> GetLinkSkillAsync(string ocid, DateOnly date, CancellationToken ct = default);
    Task<CallResult<CharacterVMatrix>> GetVMatrixAsync(string ocid, CancellationToken ct = default);
    Task<CallResult<CharacterVMatrix>> GetVMatrixAsync(string ocid, DateOnly date, CancellationToken ct = default);
    Task<CallResult<CharacterHexaMatrix>> GetHexaMatrixAsync(string ocid, CancellationToken ct = default);
    Task<CallResult<CharacterHexaMatrix>> GetHexaMatrixAsync(string ocid, DateOnly date, CancellationToken ct = default);
    Task<CallResult<CharacterHexaMatrixStat>> GetHexaMatrixStatAsync(string ocid, CancellationToken ct = default);
    Task<CallResult<CharacterHexaMatrixStat>> GetHexaMatrixStatAsync(string ocid, DateOnly date, CancellationToken ct = default);
    Task<CallResult<CharacterDojang>> GetDojangAsync(string ocid, CancellationToken ct = default);
    Task<CallResult<CharacterDojang>> GetDojangAsync(string ocid, DateOnly date, CancellationToken ct = default);
}